"""
Mochawesome JSON report parser (Cypress default reporter).
Handles both single JSON files and merged report directories.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from .base_parser import BaseParser, TestReport, TestResult, TestSuite


class MochawesomeParser(BaseParser):
    """Parser for Mochawesome JSON reports generated by Cypress."""

    def parse_file(self, filepath: str | Path) -> TestReport:
        data = self._load_json(filepath)
        return self._parse_mochawesome(data)

    def parse_directory(self, dirpath: str | Path) -> TestReport:
        """Parse all .json files in dir, merging into one report."""
        dirpath = Path(dirpath)
        json_files = sorted(dirpath.glob("**/*.json"))

        if not json_files:
            raise FileNotFoundError(f"No JSON report files found in {dirpath}")

        # Try to find a merged report first
        for f in json_files:
            if "mochawesome" in f.stem.lower() and "merge" not in f.stem.lower():
                try:
                    data = self._load_json(f)
                    if "stats" in data and "results" in data:
                        return self._parse_mochawesome(data)
                except (json.JSONDecodeError, KeyError):
                    continue

        # Otherwise parse all and merge
        combined_suites: list[TestSuite] = []
        total_duration = 0
        start_time = ""
        end_time = ""

        for f in json_files:
            try:
                data = self._load_json(f)
                if "stats" not in data or "results" not in data:
                    continue
                report = self._parse_mochawesome(data)
                combined_suites.extend(report.suites)
                total_duration += report.total_duration_ms
                if not start_time or report.start_time < start_time:
                    start_time = report.start_time
                if not end_time or report.end_time > end_time:
                    end_time = report.end_time
            except (json.JSONDecodeError, KeyError):
                continue

        return TestReport(
            framework="mochawesome",
            suites=combined_suites,
            start_time=start_time,
            end_time=end_time,
            total_duration_ms=total_duration,
        )

    def parse_html(self, filepath: str | Path) -> TestReport:
        """Parse a Mochawesome HTML file by extracting embedded JSON data."""
        path = Path(filepath)
        if not path.exists():
            raise FileNotFoundError(f"HTML report not found: {path}")

        html_content = path.read_text(encoding="utf-8")

        # Extract data-raw attribute from body tag
        match = re.search(r'data-raw="([^"]*)"', html_content)
        if not match:
            raise ValueError("Could not find embedded report data in HTML file")

        import html
        raw_json = html.unescape(match.group(1))
        data = json.loads(raw_json)
        return self._parse_mochawesome(data)

    def _parse_mochawesome(self, data: dict[str, Any]) -> TestReport:
        stats = data.get("stats", {})
        results = data.get("results", [])

        suites: list[TestSuite] = []
        for result in results:
            self._extract_suites(result, suites)

        return TestReport(
            framework="mochawesome",
            suites=suites,
            start_time=stats.get("start", ""),
            end_time=stats.get("end", ""),
            total_duration_ms=stats.get("duration", 0),
            metadata={
                "mocha_version": data.get("meta", {})
                .get("mocha", {})
                .get("version", ""),
                "mochawesome_version": data.get("meta", {})
                .get("mochawesome", {})
                .get("version", ""),
            },
        )

    def _extract_suites(
        self,
        result: dict[str, Any],
        suites: list[TestSuite],
    ) -> None:
        """Recursively extract suites and tests from result tree."""
        title = result.get("title", "")
        file_path = result.get("fullFile", result.get("file", ""))

        # Collect tests directly owned by this node
        own_tests = self._parse_tests(
            result.get("tests", []), title, file_path
        )

        children = result.get("suites", [])

        if own_tests:
            suites.append(
                TestSuite(
                    name=title or "Root",
                    file_path=file_path,
                    tests=own_tests,
                    duration_ms=result.get("duration", 0),
                )
            )

        # Recurse into child suites
        for child in children:
            self._extract_suites(child, suites)

    def _parse_tests(
        self, tests_data: list[dict], suite_name: str, file_path: str
    ) -> list[TestResult]:
        results = []
        for test in tests_data:
            err = test.get("err", {})
            error_message = err.get("message", "") if isinstance(err, dict) else ""
            error_stack = err.get("estack", "") if isinstance(err, dict) else ""

            title = test.get("title", "")
            state = test.get("state", "unknown")
            if test.get("pending"):
                state = "pending"
            if test.get("skipped"):
                state = "skipped"

            results.append(
                TestResult(
                    uuid=test.get("uuid", ""),
                    title=title,
                    full_title=test.get("fullTitle", title),
                    state=state,
                    duration_ms=test.get("duration", 0),
                    suite_name=suite_name,
                    file_path=file_path,
                    error_message=error_message,
                    error_stack=error_stack,
                    test_id=self._extract_test_id(title),
                    code_snippet=test.get("code", ""),
                    context=test.get("context"),
                )
            )
        return results
