"""
Playwright JSON report parser.
Handles reports generated by Playwright's built-in JSON reporter.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .base_parser import BaseParser, TestReport, TestResult, TestSuite


class PlaywrightParser(BaseParser):
    """Parser for Playwright JSON reports."""

    def parse_file(self, filepath: str | Path) -> TestReport:
        data = self._load_json(filepath)
        return self._parse_playwright(data)

    def parse_directory(self, dirpath: str | Path) -> TestReport:
        dirpath = Path(dirpath)
        json_files = sorted(dirpath.glob("**/*.json"))

        if not json_files:
            raise FileNotFoundError(f"No JSON report files found in {dirpath}")

        combined_suites: list[TestSuite] = []
        total_duration = 0

        for f in json_files:
            try:
                data = self._load_json(f)
                if "suites" not in data:
                    continue
                report = self._parse_playwright(data)
                combined_suites.extend(report.suites)
                total_duration += report.total_duration_ms
            except (ValueError, KeyError):
                continue

        return TestReport(
            framework="playwright",
            suites=combined_suites,
            total_duration_ms=total_duration,
        )

    def _parse_playwright(self, data: dict[str, Any]) -> TestReport:
        config = data.get("config", {})
        suites: list[TestSuite] = []

        for suite_data in data.get("suites", []):
            self._extract_suites(suite_data, suites)

        total_duration = sum(s.duration_ms for s in suites)

        return TestReport(
            framework="playwright",
            suites=suites,
            total_duration_ms=total_duration,
            metadata={
                "projects": [
                    p.get("name", "") for p in config.get("projects", [])
                ],
            },
        )

    def _extract_suites(
        self, suite_data: dict[str, Any], suites: list[TestSuite]
    ) -> None:
        tests = []
        for spec in suite_data.get("specs", []):
            for test in spec.get("tests", []):
                for result in test.get("results", []):
                    title = spec.get("title", "")
                    status = result.get("status", "unknown")
                    # Map Playwright statuses to our normalized states
                    state_map = {
                        "expected": "passed",
                        "unexpected": "failed",
                        "flaky": "passed",
                        "skipped": "skipped",
                        "timedOut": "failed",
                        "passed": "passed",
                        "failed": "failed",
                    }
                    state = state_map.get(status, status)

                    errors = result.get("errors", [])
                    error_msg = errors[0].get("message", "") if errors else ""
                    error_stack = errors[0].get("stack", "") if errors else ""

                    if not error_msg and result.get("error", {}).get("message"):
                        error_msg = result["error"]["message"]
                        error_stack = result["error"].get("stack", "")

                    tests.append(
                        TestResult(
                            uuid=spec.get("id", ""),
                            title=title,
                            full_title=f"{suite_data.get('title', '')} > {title}",
                            state=state,
                            duration_ms=result.get("duration", 0),
                            suite_name=suite_data.get("title", ""),
                            file_path=suite_data.get("file", ""),
                            error_message=error_msg,
                            error_stack=error_stack,
                            test_id=self._extract_test_id(title),
                            retry_count=result.get("retry", 0),
                        )
                    )

        if tests:
            suites.append(
                TestSuite(
                    name=suite_data.get("title", ""),
                    file_path=suite_data.get("file", ""),
                    tests=tests,
                    duration_ms=sum(t.duration_ms for t in tests),
                )
            )

        # Recurse into child suites
        for child in suite_data.get("suites", []):
            self._extract_suites(child, suites)
