"""
Pytest/Selenium JSON report parser.
Handles reports generated by pytest-json-report plugin.
"""

from __future__ import annotations

import uuid as uuid_lib
from pathlib import Path
from typing import Any

from .base_parser import BaseParser, TestReport, TestResult, TestSuite


class PytestParser(BaseParser):
    """Parser for pytest-json-report / pytest-json output."""

    def parse_file(self, filepath: str | Path) -> TestReport:
        data = self._load_json(filepath)
        return self._parse_pytest(data)

    def parse_directory(self, dirpath: str | Path) -> TestReport:
        dirpath = Path(dirpath)
        json_files = sorted(dirpath.glob("**/*.json"))

        if not json_files:
            raise FileNotFoundError(f"No JSON report files found in {dirpath}")

        combined_suites: list[TestSuite] = []
        total_duration = 0

        for f in json_files:
            try:
                data = self._load_json(f)
                if "tests" not in data:
                    continue
                report = self._parse_pytest(data)
                combined_suites.extend(report.suites)
                total_duration += report.total_duration_ms
            except (ValueError, KeyError):
                continue

        return TestReport(
            framework="pytest",
            suites=combined_suites,
            total_duration_ms=total_duration,
        )

    def _parse_pytest(self, data: dict[str, Any]) -> TestReport:
        tests_data = data.get("tests", [])
        summary = data.get("summary", {})
        env = data.get("environment", {})

        # Group tests by their module/file
        suites_map: dict[str, list[TestResult]] = {}

        for test in tests_data:
            nodeid = test.get("nodeid", "")
            # nodeid format: "tests/test_file.py::TestClass::test_method"
            parts = nodeid.split("::")
            file_path = parts[0] if parts else ""
            suite_name = parts[1] if len(parts) > 2 else file_path

            outcome = test.get("outcome", "unknown")
            state_map = {
                "passed": "passed",
                "failed": "failed",
                "error": "failed",
                "skipped": "skipped",
                "xfailed": "skipped",
                "xpassed": "passed",
            }
            state = state_map.get(outcome, outcome)

            # Extract error details from call phase
            call_info = test.get("call", {})
            error_message = ""
            error_stack = ""
            if call_info.get("longrepr"):
                error_stack = call_info["longrepr"]
                # First line is usually the assertion message
                lines = error_stack.strip().split("\n")
                error_message = lines[-1] if lines else ""

            title = parts[-1] if parts else nodeid
            duration = int(test.get("duration", 0) * 1000)

            result = TestResult(
                uuid=str(uuid_lib.uuid4()),
                title=title,
                full_title=nodeid,
                state=state,
                duration_ms=duration,
                suite_name=suite_name,
                file_path=file_path,
                error_message=error_message,
                error_stack=error_stack,
                test_id=self._extract_test_id(title),
                tags=test.get("keywords", []),
            )

            suites_map.setdefault(suite_name, []).append(result)

        suites = [
            TestSuite(
                name=name,
                file_path=tests[0].file_path if tests else "",
                tests=tests,
                duration_ms=sum(t.duration_ms for t in tests),
            )
            for name, tests in suites_map.items()
        ]

        duration_ms = int(data.get("duration", 0) * 1000)

        return TestReport(
            framework="pytest",
            suites=suites,
            start_time=data.get("created", ""),
            total_duration_ms=duration_ms,
            metadata={
                "python_version": env.get("Python", ""),
                "platform": env.get("Platform", ""),
                "summary": summary,
            },
        )
